apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-example02
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/yefercas/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./custom-diff/02-external-app
   
  destination:
    server: https://kubernetes.default.svc
    namespace: example02

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
ignoreDifferences:
    # 1. Ignora la contraseña en el Secret
    - group: ""
      kind: Secret
      name: example-secret
      jsonPointers:
        - /data/my-password
    # 2. Ignora la anotación "creation" en el Deployment
    - group: apps
      kind: Deployment
      name: simple-deployment
      jsonPointers:
        - /metadata/annotations/creation